image: debian

build:
  before_script:
  - apt-get -qqy update
  - apt-get -qqy install --no-install-recommends build-essential cmake libpng-dev git
  script:
  - mkdir build
  - cd build
  - CFLAGS="-Wall -Wextra" cmake ..
  - cmake --build .
